#15 added option for remote book
BirkbeckCTP/books pull request #17
Opened 2020-07-28 14:45 UTC by ajrbyers

Closes #15

2020-09-01 16:40 UTC, mauromsl requested changes
Nice!
Just a coupe typos to sort out

2020-09-01 16:40 UTC, mauromsl commented on migrations/0012_auto_20200728_1441.py
> +            field=models.FileField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(location='/vol/janeway/src/media'), upload_to=plugins.books.models.cover_images_upload_pa
Should use `JanewayFileSystemStorage`

2020-09-01 16:40 UTC, mauromsl commented on models.py
> +        help_text='Label for the remote link. If left blank will display as'
No whitespace in `"asview"`

2020-09-01 16:40 UTC, mauromsl commented on models.py
> +        help_text='Set this if you want to have your book link out to a remote'
no space in `"remotewebsite"`

2020-09-09 15:59 UTC, ajrbyers commented on migrations/0012_auto_20200728_1441.py
> +            field=models.FileField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(location='/vol/janeway/src/media'), upload_to=plugins.books.models.cover_images_upload_pa
Merge of #14 will fix this.

2020-09-11 16:41 UTC, mauromsl approved these changes
Cool, added a comment in #16 relevant to this. We will need to rebase that branch and recreate the migrations most likely

2020-09-11 16:41 UTC, merged