Excludes keywords and publisher notes from the chapter form.
BirkbeckCTP/books pull request #66
Opened 2024-06-25 18:36 UTC by ajrbyers

2024-08-07 09:27 UTC, mauromsl requested changes

2024-08-07 09:27 UTC, mauromsl commented on forms.py
> +        exclude = ('book', 'filename', 'keywords', 'publisher_notes')
Shall we use `include` to avoid accidental leaks such as this in the future?

2024-08-08 12:14 UTC, mauromsl approved these changes

2024-08-12 15:31 UTC, joemull approved these changes

2024-08-12 15:31 UTC, merged